### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by piscopancer** [dsh2dsh/screen_space_shaders#1]
### Here is the list of addons
![image](https://github.com/dsh2dsh/screen_space_shaders/assets/109352196/cceacb80-556a-42d2-bc15-51651e39a279)
I use MO2 btw.
I did install modded exes.
There is only one graphics specific addon in my folder called `late-fall`. I tried disabling it, still crashes.
### These are the options I selected to install:
![image](https://github.com/dsh2dsh/screen_space_shaders/assets/109352196/7c4a35ff-2e12-42d9-8e9a-92289e4a4a39)

**Comment by dsh2dsh** [comment]
This isn't my project. This is just a mirror of https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders
